In [32]:
import pandas as pd

df = pd.read_csv("balance_history.csv")
df = df.drop("Unnamed: 0", axis=1)

# Recast Amount column as float
df["Balance"] = df["Balance"].replace('[\$,]', '', regex=True).astype(float)

# Recast dates as datetime
df["Date"] = pd.to_datetime(df["Date"])
# df["Date"] = pd.to_datetime(df["Date"] + ' ' + df["Time"])
df = df.drop("Time", axis=1)
df["Month"] = pd.to_datetime(df["Month"])
df["Week"] = pd.to_datetime(df["Week"])
df["Date Added"] = pd.to_datetime(df["Date Added"])

# Use better strings for Month and Week columns
df["Month"] = df["Month"].dt.strftime('%Y-%m')
df["Week"] = df["Week"].dt.strftime('%U')


df = df[df["Account ID"] == "65440a84a14656002f355cee"]
df = df.filter(["Date", "Account", "Account ID", "Institution", "Group"])
df = df.sort_values("Date")
df = df.drop_duplicates(["Date"], keep="last")
idx = pd.date_range(df["Date"].min(), df["Date"].max())
df.index = pd.DatetimeIndex(df["Date"])
df = df.reindex(idx)
df["Date"] = df.index
df = df.fillna(method="ffill")

display(df)

,Date,Account,Account ID,Institution,Group
2023-11-02,2023-11-02,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-03,2023-11-03,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-04,2023-11-04,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-05,2023-11-05,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-06,2023-11-06,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-07,2023-11-07,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-08,2023-11-08,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-09,2023-11-09,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-10,2023-11-10,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-11,2023-11-11,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-12,2023-11-12,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-13,2023-11-13,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
2023-11-14,2023-11-14,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card

In [33]:
import pandas as pd

df = pd.read_csv("balance_history.csv")
df = df.drop("Unnamed: 0", axis=1)
df = df.drop("Time", axis=1)

# Recast Amount column as float
df["Balance"] = df["Balance"].replace('[\$,]', '', regex=True).astype(float)

# Recast dates as datetime
df["Date"] = pd.to_datetime(df["Date"])
df["Month"] = pd.to_datetime(df["Month"])
df["Week"] = pd.to_datetime(df["Week"])
df["Date Added"] = pd.to_datetime(df["Date Added"])

# Use better strings for Month and Week columns
df["Month"] = df["Month"].dt.strftime('%Y-%m')
df["Week"] = df["Week"].dt.strftime('%U')

df = df.filter(["Date", "Account", "Account ID", "Institution", "Group"])
df = df.sort_values("Date")
df = df.drop_duplicates(["Date", "Account ID"], keep="last")

idx = pd.date_range(df["Date"].min(), df["Date"].max())
df.index = pd.DatetimeIndex(df["Date"])
df = df.reindex(idx)
df["Date"] = df.index
df = df.fillna(method="ffill")

display(df)

,Date,Account,Account ID,Institution,Group
148,2023-11-02,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
136,2023-11-02,Bills,65440f6fa14656002f363274,First Horizon (Digital Banking),Checking
137,2023-11-02,Line of Credit,65440f6fa14656002f363288,First Horizon (Digital Banking),Loan
138,2023-11-02,Delta SkyMiles Gold Card,65440eeaa14656002f361c16,American Express Cards,Credit Card
139,2023-11-02,Individual ...913,65440ec86c2203002f1bcbfd,Charles Schwab,Investment
...,...,...,...,...,...
13,2023-11-13,Traditional IRA,65440e86a14656002f360ea6,Fidelity Investments,Investment
8,2023-11-13,American Airlines AAdvantage MileUp card,65451a7ea14656002f63fe23,Citibank,Credit Card
2,2023-11-14,CREDIT CARD,65440a84a14656002f355cee,Chase,Credit Card
1,2023-11-14,CREDIT CARD,65440a84a14656002f355cd9,Chase,Credit Card
0,2023-11-14,CREDIT CARD,65440a84a14656002f355cba,Chase,Credit Card

In [34]:
idx = pd.date_range(df["Date"].min(), df["Date"].max())
df.index = pd.MultiIndex(["Date", "Account ID"])
display(df)

TypeError: Must pass both levels and codes